export interface Icolumdef {
  headerName : string ,
  field : string,
  Serv: string,
  selectDisplay:string,
  selectValue:string,
  fieldgroup:number,
  groupname:string,
  parentgroup:string,
  fielddisable: boolean,
  disabled : boolean,
  ip:string,
  port:string,
  formnum:number,
  sortable: boolean, 
  filter: boolean, 
  editable: boolean,      
  resizable: boolean,
  checkboxSelection: boolean,
  cellRenderer: string
 }