CREATE TABLE IF NOT EXISTS User_login(
  ID serial primary key,
  User_tokean VARCHAR(450) NULL,
  Expire_date timestamp NULL,
  Create_date timestamp NULL,
  Username VARCHAR(450) NOT NULL,
  password_ency VARCHAR(450) NOT NULL,
  login_modfiy timestamp NOT NULL,
  login_create timestamp NOT NULL,
  User_ID INT NOT NULL,
  Notes VARCHAR(450) NULL,
  Login_key VARCHAR(450) NOT NULL,
  Group_priviledge_ID INT NOT NULL,
  login_failed INT NULL DEFAULT 0,
  User_status_ID INT NOT NULL,
  User_type_ID INT NOT NULL,
  login_flag INT NOT NULL,
  Pages_ID INT NOT NULL,
  Application_ID INT NOT NULL);